---
title: "Untitled"
author: "Zhonghao Zhan"
date: "9/22/2017"
output: html_document
---

```{r}
library(multiway)
# Define matrix dimensions
mydim <- c(101,101,3)

library(eemR)
ls("package:eemR")
cstep1 <- system.file("extdata/cary/CyclicQUV/step1/3DEEM/", package = "eemR")
eemsc1 <- eem_read(cstep1)

summary(eemsc1)




# Create testing matrices

#Amat <- matrix(rnorm(eemsc1[1]*101),eemsc1[1],101)
#Bmat <- matrix(runif(eemsc1[2]*101),eemsc1[2],101)
#Cmat <- matrix(runif(eemsc1[2]*101),eemsc1[2],101)

#Combine testing matrices into one large matrix
#X <- array(c(Amat,Bmat,Cmat),dim=mydim)

# Parafac modeling
#pfac <- parafac(eemsc1,nfac=3,nstart=1)

#########For extracting data matrices from eemR objects

library(eemR)
library(EEM)

ls("package:eemR")
cstep1 <- system.file("extdata/cary/CyclicQUV/step1/3DEEM/sa25000-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)

# Example of extracting matrix from eemlist object
v1 <- eemsc1[[1]]$x
v2 <- eemsc1[[1]]$x
v3 <- eemsc1[[1]]$x

# Combine matrices into one large "Array"
# dimensions: (emission, excitation, step); check to see what was done in paper

mydim <- c(501,101,3)
X <- array(c(v1,v2,v3),dim=mydim)

# Set up PARAFAC analysis

pfac <- parafac(X,nfac=3,nstart=1)
```

```{r}
# sa25000-cyclicQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25000-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/CyclicQUV/step1/3DEEM/sa25000-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/CyclicQUV/step2/3DEEM/sa25000-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/CyclicQUV/step3/3DEEM/sa25000-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/CyclicQUV/step4/3DEEM/sa25000-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)


eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]


eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc1)


a0 <- eemsc0[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat


plot(em.test, which = 1)

plot(pfac$C)
plot(pfac$B)
```

```{r}
# sa25002-cyclicQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25002-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/CyclicQUV/step1/3DEEM/sa25002-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/CyclicQUV/step2/3DEEM/sa25002-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/CyclicQUV/step3/3DEEM/sa25002-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/CyclicQUV/step4/3DEEM/sa25002-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)

a0 <- eemsc0[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat

plot(em.test, which = 1)
```

```{r}
# sa25004-cyclicQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25004-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/CyclicQUV/step1/3DEEM/sa25004-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/CyclicQUV/step2/3DEEM/sa25004-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/CyclicQUV/step3/3DEEM/sa25004-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/CyclicQUV/step4/3DEEM/sa25004-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)

a0 <- eemsc0[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat

plot(em.test, which = 1)
```

```{r}
# sa25006-cyclicQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25006-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/CyclicQUV/step1/3DEEM/sa25006-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/CyclicQUV/step2/3DEEM/sa25006-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/CyclicQUV/step3/3DEEM/sa25006-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/CyclicQUV/step4/3DEEM/sa25006-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)

a0 <- eemsc0[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat

plot(em.test, which = 1)
```

```{r}
# sa25008-cyclicQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25008-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/CyclicQUV/step1/3DEEM/sa25008-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/CyclicQUV/step2/3DEEM/sa25008-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/CyclicQUV/step3/3DEEM/sa25008-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/CyclicQUV/step4/3DEEM/sa25008-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x
a0 <- eemsc0[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat


plot(em.test, which = 1)
```

```{r}
# sa25010-cyclicQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25010-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)

cstep1 <- system.file("extdata/cary/CyclicQUV/step1/3DEEM/sa25010-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/CyclicQUV/step2/3DEEM/sa25010-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/CyclicQUV/step3/3DEEM/sa25010-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/CyclicQUV/step4/3DEEM/sa25010-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a0 <- eemsc0[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat



test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat


plot(em.test, which = 1)
```

```{r}
# sa25000-HotQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25000-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/HotQUV/step1/3DEEM/sa25000-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/HotQUV/step2/3DEEM/sa25000-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/HotQUV/step3/3DEEM/sa25000-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/HotQUV/step4/3DEEM/sa25000-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]


eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)

a0 <- eemsc0[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat

plot(em.test, which = 1)
```
```{r}
# sa25002-HotQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25002-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/HotQUV/step1/3DEEM/sa25002-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/HotQUV/step2/3DEEM/sa25002-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/HotQUV/step3/3DEEM/sa25002-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/HotQUV/step4/3DEEM/sa25002-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc0, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)




a0 <- eemsc0[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat

plot(em.test, which = 1)
```
```{r}
# sa25004-HotQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25004-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/HotQUV/step1/3DEEM/sa25004-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/HotQUV/step2/3DEEM/sa25004-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/HotQUV/step3/3DEEM/sa25004-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/HotQUV/step4/3DEEM/sa25004-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)

a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```

```{r}
# sa25006-HotQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25006-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/HotQUV/step1/3DEEM/sa25006-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/HotQUV/step2/3DEEM/sa25006-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/HotQUV/step3/3DEEM/sa25006-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/HotQUV/step4/3DEEM/sa25006-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```

```{r}
# sa25008-HotQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25008-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/HotQUV/step1/3DEEM/sa25008-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/HotQUV/step2/3DEEM/sa25008-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/HotQUV/step3/3DEEM/sa25008-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/HotQUV/step4/3DEEM/sa25008-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```

```{r}
# sa25010-HotQUV

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25010-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/HotQUV/step1/3DEEM/sa25010-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/HotQUV/step2/3DEEM/sa25010-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/HotQUV/step3/3DEEM/sa25010-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/HotQUV/step4/3DEEM/sa25010-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```

```{r}
# sa25000-DampHeat

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25000-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/DampHeat/step1/3DEEM/sa25000-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/DampHeat/step2/3DEEM/sa25000-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/DampHeat/step3/3DEEM/sa25000-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/DampHeat/step4/3DEEM/sa25000-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)

a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```
```{r}
# sa25002-DampHeat

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25002-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/DampHeat/step1/3DEEM/sa25002-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/DampHeat/step2/3DEEM/sa25002-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/DampHeat/step3/3DEEM/sa25002-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/DampHeat/step4/3DEEM/sa25002-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```

```{r}
# sa25004-DampHeat

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25004-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/DampHeat/step1/3DEEM/sa25004-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/DampHeat/step2/3DEEM/sa25004-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/DampHeat/step3/3DEEM/sa25004-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/DampHeat/step4/3DEEM/sa25004-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```
```{r}
# sa25006-DampHeat

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25006-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/DampHeat/step1/3DEEM/sa25006-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/DampHeat/step2/3DEEM/sa25006-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/DampHeat/step3/3DEEM/sa25006-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/DampHeat/step4/3DEEM/sa25006-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```

```{r}
# sa25008-DampHeat

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25008-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/DampHeat/step1/3DEEM/sa25008-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/DampHeat/step2/3DEEM/sa25008-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/DampHeat/step3/3DEEM/sa25008-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/DampHeat/step4/3DEEM/sa25008-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```
```{r}
# sa25010-DampHeat

library(eemR)
library(EEM)
library(multiway)
ls("package:eemR")

cstep0 <- system.file("extdata/cary/Baseline/sa25010-step0.csv", package = "eemR")
eemsc0 <- eem_read(cstep0)
cstep1 <- system.file("extdata/cary/DampHeat/step1/3DEEM/sa25010-step1.csv", package = "eemR")
eemsc1 <- eem_read(cstep1)
cstep2 <- system.file("extdata/cary/DampHeat/step2/3DEEM/sa25010-step2.csv", package = "eemR")
eemsc2 <- eem_read(cstep2)
cstep3 <- system.file("extdata/cary/DampHeat/step3/3DEEM/sa25010-step3.csv", package = "eemR")
eemsc3 <- eem_read(cstep3)
cstep4 <- system.file("extdata/cary/DampHeat/step4/3DEEM/sa25010-step4.csv", package = "eemR")
eemsc4 <- eem_read(cstep4)

eemsc0[[1]]$em<-eemsc0[[1]]$em[1:501]
eemsc0[[1]]$x<-eemsc0[[1]]$x[c(1:501),c(1:101)]
eemsc1[[1]]$em<-eemsc1[[1]]$em[1:501]
eemsc1[[1]]$x<-eemsc1[[1]]$x[c(1:501),c(1:101)]
eemsc2[[1]]$em<-eemsc2[[1]]$em[1:501]
eemsc2[[1]]$x<-eemsc2[[1]]$x[c(1:501),c(1:101)]
eemsc3[[1]]$em<-eemsc3[[1]]$em[1:501]
eemsc3[[1]]$x<-eemsc3[[1]]$x[c(1:501),c(1:101)]
eemsc4[[1]]$em<-eemsc4[[1]]$em[1:501]
eemsc4[[1]]$x<-eemsc4[[1]]$x[c(1:501),c(1:101)]

eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc0 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 1, 20)
eemsc1 <- eem_remove_scattering(eemsc1, "rayleigh", 2, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 1, 20)
eemsc2 <- eem_remove_scattering(eemsc2, "rayleigh", 2, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 1, 20)
eemsc3 <- eem_remove_scattering(eemsc3, "rayleigh", 2, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 1, 20)
eemsc4 <- eem_remove_scattering(eemsc4, "rayleigh", 2, 20)

plot(eemsc2)


a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

a0 <- eemsc1[[1]]$x
a1 <- eemsc1[[1]]$x
a2 <- eemsc2[[1]]$x
a3 <- eemsc3[[1]]$x
a4 <- eemsc4[[1]]$x

testdim <- c(501,101,5)
testarray <- array(c(a0,a1,a2,a3,a4),dim=testdim)

testarray[is.na(testarray)] <- 0
testarray[testarray < 0] <- 0

pfac <- parafac(testarray,nfac=1,nstart=1, const=c(2,2,2))

test <- fitted(pfac)

em.test <- eemsc2

test.mat <- as.matrix(test[,,1])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,2])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,3])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,4])
em.test[[1]]$x <- test.mat

test.mat <- as.matrix(test[,,5])
em.test[[1]]$x <- test.mat



plot(em.test, which = 1)
```
